version: "3.8"

services:
  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge
