services:
  gameservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - GAMESERVICE_HOST=gameservice
      - MATCHMAKINGSERVICE_HOST=matchmakingservice
  matchmakingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
