version: "3.8"

services:
  gameservice:
    container_name: gameservice
    image: gameservice:latest
    build:
      context: ./GameService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_HOST=redis:6379
      - ConnectionStrings__Redis=redis:6379
    networks:
      - chess-network

  apigateway:
    container_name: apigateway
    image: apigateway:latest
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
      - GAMESERVICE_HOST=gameservice
      - AUTHSERVICE_HOST=authservice
      - MATCHMAKINGSERVICE_HOST=matchmakingservice
      - REDIS_HOST=redis:6379
    depends_on:
      - gameservice
      - matchmakingservice
    networks:
      - chess-network

  matchmakingservice:
    container_name: matchmakingservice
    image: matchmakingservice:latest
    build:
      context: ./MatchmakingService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8082
    networks:
      - chess-network

  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - chess-network

  mongo:
    image: mongo:latest
    container_name: auth-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: authdb
    networks:
      - chess-network

  authservice:
    container_name: authservice
    image: authservice:latest
    build:
      context: ./Authservice
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8084
      - ConnectionString=mongodb://mongo:27017/authdb
      - EMAIL_VERIFICATION_BASE_URL=http://localhost:3000/verify
    env_file:
      - ./Authservice/src/Authservice.API/.env
    depends_on:
      - mongo
    networks:
      - chess-network

  gameservice-tests:
    container_name: gameservice-tests
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./GameService:/app
    working_dir: /app
    command: dotnet test /app/test/GameService.Tests/GameService.Tests.csproj --logger "trx"
    depends_on:
      - gameservice
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge
