version: "3.8"

services:
  gameservice:
    container_name: gameservice
    image: gameservice:latest
    build:
      context: ./GameService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080

    networks:
      - chess-network

  apigateway:
    container_name: apigateway
    image: apigateway:latest
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
      - GAMESERVICE_HOST=gameservice
      - MATCHMAKINGSERVICE_HOST=matchmakingservice
    depends_on:
      - gameservice
      - matchmakingservice
    networks:
      - chess-network

  matchmakingservice:
    container_name: matchmakingservice
    image: matchmakingservice:latest
    build:
      context: ./MatchmakingService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8082
    networks:
      - chess-network

  gameservice-tests:
    container_name: gameservice-tests
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./GameService:/app
    working_dir: /app
    command: dotnet test /app/test/GameService.Tests/GameService.Tests.csproj --logger "trx"
    depends_on:
      - gameservice
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge
