version: "3.8"

services:
  gameservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - GAMESERVICE_HOST=localhost
      - MATCHMAKINGSERVICE_HOST=localhost
  matchmakingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
