apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: duckdns-cert
  namespace: default
spec:
  secretName: duckdns-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: chessworldexampledns.duckdns.org
  dnsNames:
    - chessworldexampledns.duckdns.org
