apiVersion: apps/v1
kind: Deployment
metadata:
  name: chessworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chessworld
  template:
    metadata:
      labels:
        app: chessworld
    spec:
      containers:
        - name: frontend
          image: rowanbattles/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        - name: apigateway
          image: rowanbattles/apigateway:latest
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: GAMESERVICE_HOST
              value: "gameservice"
            - name: MATCHMAKINGSERVICE_HOST
              value: "matchmakingservice"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
        - name: gameservice
          image: rowanbattles/gameservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        - name: matchmakingservice
          image: rowanbattles/matchmakingservice:latest
          ports:
            - containerPort: 8082
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: ASPNETCORE_URLS
              value: "http://+:8082"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
