apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chessworld-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /apigateway
            pathType: Prefix
            backend:
              service:
                name: apigateway
                port:
                  number: 5000
