apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: chessworld
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: gameservice
spec:
  selector:
    app: chessworld
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: matchmakingservice
spec:
  selector:
    app: chessworld
  ports:
    - port: 8082
      targetPort: 8082
