name: Continuous Integration Pipeline

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Run Linter
        run: yarn lint

      - name: Build Frontend
        run: yarn build

      - name: Build and Push Frontend Docker Image
        run: |
          docker build --build-arg VITE_API_URL=https://chessworldexampledns.duckdns.org/api -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Backend Services
        run: docker-compose -f docker-compose.yml build

      - name: Start Backend Services
        run: docker-compose -f docker-compose.yml up -d

      - name: Run Backend Tests
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from gameservice-tests

      - name: Tear Down Backend Services
        run: docker-compose -f docker-compose.yml down

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push Backend Images
        run: |
          docker tag gameservice ${{ secrets.DOCKERHUB_USERNAME }}/gameservice:latest
          docker tag matchmakingservice ${{ secrets.DOCKERHUB_USERNAME }}/matchmakingservice:latest
          docker tag apigateway ${{ secrets.DOCKERHUB_USERNAME }}/apigateway:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gameservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/matchmakingservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/apigateway:latest
